# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.
all:
  vars:
    single_node: true
    users:
      # Provision user for OpenCRVS deployment (de-alwis.com QA environment)
      - name: provision
        ssh_keys:
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMN8jw0bD+1eVIjFGknFEGRMtGn/iRXI28tIt8YpVQRp root@srv1348228
        state: present
        sudoer: true

docker-manager-first:
  hosts:
    srv1348228.hstgr.cloud:
      ansible_host: '76.13.183.142'
      data_label: data1

# QA and staging servers are not configured to use workers.
docker-workers: {}
